steps:
  # 1. 构建 Docker 镜像 (使用 Artifact Registry)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-south1-docker.pkg.dev/$PROJECT_ID/report-general/auto-report-service:$SHORT_SHA', '.']

  # 2. 推送镜像到 Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-south1-docker.pkg.dev/$PROJECT_ID/report-general/auto-report-service:$SHORT_SHA']

  # 3. 部署到 Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'reportgeneral'
      - '--image'
      - 'asia-south1-docker.pkg.dev/$PROJECT_ID/report-general/auto-report-service:$SHORT_SHA'
      - '--region'
      - 'asia-south1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '2Gi'

options:
  logging: CLOUD_LOGGING_ONLY
